FROM node:20-alpine

ARG CONTACT_MAIL_AUTH_USERNAME
ARG CONTACT_MAIL_AUTH_PASSWORD
ARG AUTH_GOOGLE_CLIENT_SECRET
ARG CONTACT_MAIL_AUTH_PORT
ARG CONTACT_MAIL_AUTH_HOST
ARG AUTH_GOOGLE_CLIENT_ID
ARG CONTACT_MAIL_RECEIVER
ARG NEXT_PUBLIC_APP_URL
ARG CONTACT_MAIL_SENDER
ARG NEXT_PUBLIC_API_URL
ARG AUTH_SECRET
ARG AUTH_URL

ENV CONTACT_MAIL_AUTH_USERNAME=$CONTACT_MAIL_AUTH_USERNAME \
  CONTACT_MAIL_AUTH_PASSWORD=$CONTACT_MAIL_AUTH_PASSWORD \
  AUTH_GOOGLE_CLIENT_SECRET=$AUTH_GOOGLE_CLIENT_SECRET \
  CONTACT_MAIL_AUTH_PORT=$CONTACT_MAIL_AUTH_PORT \
  CONTACT_MAIL_AUTH_HOST=$CONTACT_MAIL_AUTH_HOST \
  AUTH_GOOGLE_CLIENT_ID=$AUTH_GOOGLE_CLIENT_ID \
  CONTACT_MAIL_RECEIVER=$CONTACT_MAIL_RECEIVER \
  NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL  \
  CONTACT_MAIL_SENDER=$CONTACT_MAIL_SENDER  \
  NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL  \
  AUTH_SECRET=$AUTH_SECRET  \
  AUTH_URL=$AUTH_URL

WORKDIR /usr/app

COPY . .

RUN npm ci

# COPY .env .env

RUN npm run build

CMD ["npm", "start"]