FROM node:20-alpine

ARG NEXT_PUBLIC_APP_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG AUTH_URL

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL  \
  NEXTAUTH_SECRET=$NEXTAUTH_SECRET  \
  NEXTAUTH_URL=$NEXTAUTH_URL  \
  AUTH_URL=$AUTH_URL

WORKDIR /usr/app

COPY . .

RUN npm ci

# COPY .env .env

RUN npm run build

CMD ["npm", "start"]