server {
  listen 3000;

  location /_next/static/ {
    root /app;
    expires 365d;
  }

  location /public/ {
    root /app;
    expires 365d;
  }

  location / {
    try_files $uri $uri/ /index.html;
    root /app/.next/standalone;
  }
}