// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata, Viewport } from 'next';

import { ContentWrapper, LayoutWrapper } from '@/components/shared/layout/styled';
import AntDesignThemeProvider from '@/components/shared/theme/provider';
import NextAuthProvider from '@/components/shared/auth-provider';
import ThemeSwitch from '@/components/shared/theme/switch';
import Alert from '@/components/shared/feedback/alert';
import Header from '@/components/shared/layout/header';
import Navbar from '@/components/shared/layout/navbar';
import Footer from '@/components/shared/layout/footer';
import { fontClassNames } from '@/libs/fonts';
import ReduxProvider from '@/store/provider';
import { inProduction } from '@/utils';
import GlobalStyles from '@/styles';
import colors from '@/libs/colors';

// export const viewport: Viewport = {
//   themeColor: [
//     { media: '(prefers-color-scheme: light)', color: colors.theme.primary },
//     { media: '(prefers-color-scheme: dark)', color: colors.theme.primary }
//   ],
//   width: 'device-width',
//   initialScale: 1,
//   maximumScale: 1
// };

export const metadata: Metadata = {
  keywords: ['Business', 'Artisans', 'Buyers', 'Sellers', 'Online Market', 'Sales'],
  // metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL),
  referrer: 'origin-when-cross-origin',
  description: 'Algrith Website',
  manifest: '/app.webmanifest',
  applicationName: 'Algrith',
  publisher: 'Algrith LLC',
  creator: 'Algrith LLC',
  openGraph: {
    // url: process.env.NEXT_PUBLIC_APP_URL,
    description: 'Algrith Website',
    siteName: 'Algrith',
    title: 'Algrith',
    locale: 'en_US',
    type: 'website',
    images: []
  },
  icons: {},
  title: {
    template: '%s | Algrith',
    default: 'Algrith'
  },
  robots: {
    nocache: !inProduction,
    follow: inProduction,
    index: inProduction,
    googleBot: {
      noimageindex: inProduction,
      follow: inProduction,
      index: inProduction,
    },
  }
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => (
  <ReduxProvider>
    <NextAuthProvider>
      <html lang="en-US">
        <body className={fontClassNames}>
          <GlobalStyles />

          <AntDesignThemeProvider>
            <LayoutWrapper>
              <LayoutWrapper>
                <Header />
                <Navbar />
                <ThemeSwitch />

                <ContentWrapper>
                  {children}
                </ContentWrapper>

                <Alert />
                <Footer />
              </LayoutWrapper>
            </LayoutWrapper>
          </AntDesignThemeProvider>
        </body>
      </html>
    </NextAuthProvider>
  </ReduxProvider>
);

export default RootLayout;