name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Use a service account with Cloud Run Admin role
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.repository }} --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} --build-arg NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ github.repository }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.repository }} \
            --region your-cloud-run-region \ # Replace with your region
            --platform managed \
            --allow-unauthenticated # If you want to allow public access