name: Development - Google Cloud Run

on:
  push:
    branches:
      - feature-**
      - develop
  pull_request:
    types: [synchronize, reopened, opened, closed]
    branches:
      - develop

jobs:
  build_and_deploy_job:
    uses: ./.github/workflows/development-deployment.yaml
    if: startsWith(github.ref, 'refs/heads/feature-ALG-')
    name: Development Deployment Job
    secrets: inherit
    permissions: 
      id-token: write
      contents: read
    with: 
      environment: development
      ref: ${{ github.sha }}


# - name: Build Docker Image
#   uses: docker/build-push-action@v2
#   with:
#     # tags: ${{ secrets.AZURE_PRODUCTION_CONTAINER_ENDPOINT }}/megaquestapp:latest
#     file: Dockerfile
#     build-args: |
#       AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}
#       AUTH_GOOGLE_CLIENT_ID=${{ secrets.AUTH_GOOGLE_CLIENT_ID }}
#       NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
#       AUTH_SECRET=${{ secrets.AUTH_SECRET }}
#       AUTH_URL=${{ secrets.AUTH_URL }}