name: Production - Google Cloud Run

on:
  push:
    branches:
      - main
    tags:
      - deploy-production-v**

jobs:
  deploy:
    # if: startsWith(github.ref, 'refs/tags/deploy-production-v')
    environment: production
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'
        
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.SERVICE }}:${{ github.sha }}"
        
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.SERVICE }}
          region: ${{ secrets.REGION }}
          image: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/${{ secrets.SERVICE }}:${{ github.sha }}
          env_vars: |
            NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
            CONTACT_MAIL_AUTH_USERNAME=${{ secrets.CONTACT_MAIL_AUTH_USERNAME }}
            CONTACT_MAIL_AUTH_PASSWORD=${{ secrets.CONTACT_MAIL_AUTH_PASSWORD }}
            AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}
            CONTACT_MAIL_AUTH_PORT=${{ secrets.CONTACT_MAIL_AUTH_PORT }}
            CONTACT_MAIL_AUTH_HOST=${{ secrets.CONTACT_MAIL_AUTH_HOST }}
            AUTH_GOOGLE_CLIENT_ID=${{ secrets.AUTH_GOOGLE_CLIENT_ID }}
            CONTACT_MAIL_RECEIVER=${{ secrets.CONTACT_MAIL_RECEIVER }}
            RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            CONTACT_MAIL_SENDER=${{ secrets.CONTACT_MAIL_SENDER }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_URL=${{ secrets.AUTH_URL }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}