name: Staging - Google Cloud Run

on:
  push:
    branches:
      - release-v**
    tags:
      - deploy-staging-v**

jobs:
  build_and_deploy_job:
    if: startsWith(github.ref, 'refs/tags/deploy-staging-v')
    uses: ./.github/workflows/staging-deployment.yaml
    name: Staging Deployment Job
    secrets: inherit
    permissions: 
      id-token: write
      contents: read
    with:
      ref: ${{ github.sha }}
      environment: staging


# - name: Build Docker Image
#   uses: docker/build-push-action@v2
#   with:
#     # tags: ${{ secrets.AZURE_PRODUCTION_CONTAINER_ENDPOINT }}/megaquestapp:latest
#     file: Dockerfile
#     build-args: |
#       AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}
#       AUTH_GOOGLE_CLIENT_ID=${{ secrets.AUTH_GOOGLE_CLIENT_ID }}
#       NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
#       AUTH_SECRET=${{ secrets.AUTH_SECRET }}
#       AUTH_URL=${{ secrets.AUTH_URL }}